-- Migration: Initial create Users and Tasks tables
-- Run this on Supabase SQL editor or psql connected to your database
CREATE TABLE IF NOT EXISTS public."Users" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public."Tasks" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(1024) NOT NULL,
    done boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    user_id bigint NOT NULL,
    CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES public."Users" (id) ON DELETE CASCADE
);
-- Optional: index on user_id to speed up queries per user
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON public."Tasks" (user_id);
-- Ensure unique email
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON public."Users" ("Email");